services:
  app:
    build: .
    environment:
      REDIS_HOST: redis
      COOKIE_SECRET: sehrGeheim
      WEB_DEBUG: yes
      WEB_PORT: 8888
    ports:
      8888:8888
  redis:
    image: redis:latest
